export default {
  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
  GET_TRANSACTIONS_SUCCESS: 'GET_TRANSACTIONS_SUCCESS',
  GET_TRANSACTIONS_FAILURE: 'GET_TRANSACTIONS_FAILURE',
  
  SET_TRANSACTION: 'SET_TRANSACTION',
  SET_TRANSACTION_SUCCESS: 'SET_TRANSACTION_SUCCESS',
  SET_TRANSACTION_FAILURE: 'SET_TRANSACTION_FAILURE',
  
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  DELETE_TRANSACTION_SUCCESS: 'DELETE_TRANSACTION_SUCCESS',
  DELETE_TRANSACTION_FAILURE: 'DELETE_TRANSACTION_FAILURE',
}
