export default {
  GET_MATERIALS: 'GET_MATERIALS',
  GET_MATERIALS_SUCCESS: 'GET_MATERIALS_SUCCESS',
  GET_MATERIALS_FAILURE: 'GET_MATERIALS_FAILURE',
  
  SET_MATERIAL: 'SET_MATERIAL',
  SET_MATERIAL_SUCCESS: 'SET_MATERIAL_SUCCESS',
  SET_MATERIAL_FAILURE: 'SET_MATERIAL_FAILURE',
  
  DELETE_MATERIAL: 'DELETE_MATERIAL',
  DELETE_MATERIAL_SUCCESS: 'DELETE_MATERIAL_SUCCESS',
  DELETE_MATERIAL_FAILURE: 'DELETE_MATERIAL_FAILURE',
}
